[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.1"

[prune]
  go-tests = true
  unused-packages = true
