#!/bin/bash

build_img=zexi/lxcfs-build

docker build . -f ./Dockerfile.build -t $build_img

docker run --rm -v $(pwd):/tmp $build_img cp /lxcfs/lxcfs /lxcfs/.libs/liblxcfs.so /tmp

echo "Copy lxcfs bin: $(readlink -f ./lxcfs)"
echo "Copy liblxcfs.so: $(readlink -f ./liblxcfs.so)"
