FROM frolvlad/alpine-glibc:glibc-2.28
RUN apk update && apk --no-cache add fuse fuse-dev
ADD ./lxcfs /lxcfs/lxcfs
ADD ./liblxcfs.so  /usr/local/lib/lxcfs/

STOPSIGNAL SIGINT

CMD ["/lxcfs/lxcfs", "-f", "/var/lib/lxcfs"]
